### ISSUE TITLE
Research Brewery APIs

### ISSUE THREAD

**Issue by Sarah-Git** [jwchoquette/project-number-1#8]
## Tasks/Acceptance Criteria
- [x] Research OpenBrewery DB
- [x] Research other Brewery APIs
- [x] Review with Group/Jordan
